/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.corefin.server;

import org.junit.jupiter.api.Test;

class ServerApplicationTest {
    @Test
    public void test() {
    }
}
